meta:
    ADDON_NAME = ofxPCL
    ADDON_DESCRIPTION = Addon for PointCloudLibrary
    ADDON_AUTHOR = Fumiya Funatsu
    ADDON_TAGS = pointcloudlibrary, pcl
    ADDON_URL = https://github.com/funatsufumiya/ofxPCL

common:

vs:
    ADDON_INCLUDES += "./include/"
    ADDON_INCLUDES += "./include/pcl-1.13/"

    ADDON_LIBS += "./lib/pcl_common.lib"
    ADDON_LIBS += "./lib/pcl_commond.lib"
    ADDON_LIBS += "./lib/pcl_features.lib"
    ADDON_LIBS += "./lib/pcl_featuresd.lib"
    ADDON_LIBS += "./lib/pcl_filters.lib"
    ADDON_LIBS += "./lib/pcl_filtersd.lib"
    ADDON_LIBS += "./lib/pcl_io.lib"
    ADDON_LIBS += "./lib/pcl_iod.lib"
    ADDON_LIBS += "./lib/pcl_io_ply.lib"
    ADDON_LIBS += "./lib/pcl_io_plyd.lib"
    ADDON_LIBS += "./lib/pcl_kdtree.lib"
    ADDON_LIBS += "./lib/pcl_kdtreed.lib"
    ADDON_LIBS += "./lib/pcl_keypoints.lib"
    ADDON_LIBS += "./lib/pcl_keypointsd.lib"
    ADDON_LIBS += "./lib/pcl_ml.lib"
    ADDON_LIBS += "./lib/pcl_mld.lib"
    ADDON_LIBS += "./lib/pcl_octree.lib"
    ADDON_LIBS += "./lib/pcl_octreed.lib"
    ADDON_LIBS += "./lib/pcl_outofcore.lib"
    ADDON_LIBS += "./lib/pcl_outofcored.lib"
    ADDON_LIBS += "./lib/pcl_people.lib"
    ADDON_LIBS += "./lib/pcl_peopled.lib"
    ADDON_LIBS += "./lib/pcl_recognition.lib"
    ADDON_LIBS += "./lib/pcl_recognitiond.lib"
    ADDON_LIBS += "./lib/pcl_registration.lib"
    ADDON_LIBS += "./lib/pcl_registrationd.lib"
    ADDON_LIBS += "./lib/pcl_sample_consensus.lib"
    ADDON_LIBS += "./lib/pcl_sample_consensusd.lib"
    ADDON_LIBS += "./lib/pcl_search.lib"
    ADDON_LIBS += "./lib/pcl_searchd.lib"
    ADDON_LIBS += "./lib/pcl_segmentation.lib"
    ADDON_LIBS += "./lib/pcl_segmentationd.lib"
    ADDON_LIBS += "./lib/pcl_stereo.lib"
    ADDON_LIBS += "./lib/pcl_stereod.lib"
    ADDON_LIBS += "./lib/pcl_surface.lib"
    ADDON_LIBS += "./lib/pcl_surfaced.lib"
    ADDON_LIBS += "./lib/pcl_tracking.lib"
    ADDON_LIBS += "./lib/pcl_trackingd.lib"
    ADDON_LIBS += "./lib/pcl_visualization.lib"
    ADDON_LIBS += "./lib/pcl_visualizationd.lib"

    ADDON_DLLS_TO_COPY += "./bin/pcl_common.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_commond.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_features.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_featuresd.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_filters.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_filtersd.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_io.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_iod.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_io_ply.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_io_plyd.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_kdtree.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_kdtreed.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_keypoints.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_keypointsd.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_ml.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_mld.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_octree.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_octreed.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_outofcore.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_outofcored.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_people.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_peopled.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_recognition.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_recognitiond.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_registration.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_registrationd.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_sample_consensus.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_sample_consensusd.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_search.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_searchd.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_segmentation.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_segmentationd.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_stereo.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_stereod.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_surface.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_surfaced.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_tracking.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_trackingd.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_visualization.dll"
    ADDON_DLLS_TO_COPY += "./bin/pcl_visualizationd.dll"

osx:
    ADDON_INCLUDES += "./include/pcl-1.13/"
    ADDON_INCLUDES += "./include/eigen3/"
    
    ADDON_LIBS += ./lib/libpcl_apps.dylib
    ADDON_LIBS += ./lib/libpcl_common.dylib
    ADDON_LIBS += ./lib/libpcl_features.dylib
    ADDON_LIBS += ./lib/libpcl_filters.dylib
    ADDON_LIBS += ./lib/libpcl_io.dylib
    ADDON_LIBS += ./lib/libpcl_io_ply.dylib
    ADDON_LIBS += ./lib/libpcl_kdtree.dylib
    ADDON_LIBS += ./lib/libpcl_keypoints.dylib
    ADDON_LIBS += ./lib/libpcl_ml.dylib
    ADDON_LIBS += ./lib/libpcl_octree.dylib
    ADDON_LIBS += ./lib/libpcl_outofcore.dylib
    ADDON_LIBS += ./lib/libpcl_people.dylib
    ADDON_LIBS += ./lib/libpcl_recognition.dylib
    ADDON_LIBS += ./lib/libpcl_registration.dylib
    ADDON_LIBS += ./lib/libpcl_sample_consensus.dylib
    ADDON_LIBS += ./lib/libpcl_search.dylib
    ADDON_LIBS += ./lib/libpcl_segmentation.dylib
    ADDON_LIBS += ./lib/libpcl_simulation.dylib
    ADDON_LIBS += ./lib/libpcl_simulation_io.dylib
    ADDON_LIBS += ./lib/libpcl_stereo.dylib
    ADDON_LIBS += ./lib/libpcl_surface.dylib
    ADDON_LIBS += ./lib/libpcl_tracking.dylib
    ADDON_LIBS += ./lib/libpcl_visualization.dylib
